package practica2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author jorgecasarez
 */
public class panelcito extends javax.swing.JFrame {

    /**
     * Creates new form panelcito
     */// Declaración del JTable
   
    public panelcito() {
        initComponents();
        cargarDatos();
        idPanel.setVisible(false);
        nombrePanel.setVisible(false);
        domicilioPanel.setVisible(false);
        ciudadPanel.setVisible(false);
        edadPanel.setVisible(false);
        oficioPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        noControlGroup = new javax.swing.ButtonGroup();
        edadGroup = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nombrePanel = new javax.swing.JPanel();
        nombreField = new javax.swing.JTextField();
        idPanel = new javax.swing.JPanel();
        controlRb1 = new javax.swing.JRadioButton();
        controlRb2 = new javax.swing.JRadioButton();
        controlRb3 = new javax.swing.JRadioButton();
        controlRb4 = new javax.swing.JRadioButton();
        controlRb5 = new javax.swing.JRadioButton();
        controlRb6 = new javax.swing.JRadioButton();
        noControlField = new javax.swing.JTextField();
        noControl = new javax.swing.JCheckBox();
        ciudadPanel = new javax.swing.JPanel();
        ciudadField = new javax.swing.JTextField();
        domicilioPanel = new javax.swing.JPanel();
        domicilioField = new javax.swing.JTextField();
        nombreCheckbox = new javax.swing.JCheckBox();
        domicilioCheckbox = new javax.swing.JCheckBox();
        ciudadCheckbox = new javax.swing.JCheckBox();
        predicado = new javax.swing.JButton();
        edadPanel = new javax.swing.JPanel();
        edadRb1 = new javax.swing.JRadioButton();
        edadRb4 = new javax.swing.JRadioButton();
        edadRb2 = new javax.swing.JRadioButton();
        edadRb3 = new javax.swing.JRadioButton();
        edadRb5 = new javax.swing.JRadioButton();
        edadRb6 = new javax.swing.JRadioButton();
        edadField = new javax.swing.JTextField();
        oficioPanel = new javax.swing.JPanel();
        oficioField = new javax.swing.JTextField();
        edadCheckbox = new javax.swing.JCheckBox();
        oficioCheckbox = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Frag. Horizontal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No. Control", "Nombre", "Domicilio", "Ciudad", "Edad", "Oficio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jLabel1.setText("Creación de predicado simple");

        javax.swing.GroupLayout nombrePanelLayout = new javax.swing.GroupLayout(nombrePanel);
        nombrePanel.setLayout(nombrePanelLayout);
        nombrePanelLayout.setHorizontalGroup(
            nombrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nombrePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nombrePanelLayout.setVerticalGroup(
            nombrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nombrePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        noControlGroup.add(controlRb1);
        controlRb1.setText("<");

        noControlGroup.add(controlRb2);
        controlRb2.setText(">");

        noControlGroup.add(controlRb3);
        controlRb3.setText("<=");

        noControlGroup.add(controlRb4);
        controlRb4.setText(">=");

        noControlGroup.add(controlRb5);
        controlRb5.setText("=");

        noControlGroup.add(controlRb6);
        controlRb6.setText("<>");
        controlRb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlRb6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idPanelLayout = new javax.swing.GroupLayout(idPanel);
        idPanel.setLayout(idPanelLayout);
        idPanelLayout.setHorizontalGroup(
            idPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(controlRb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlRb2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlRb3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlRb4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(controlRb5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(controlRb6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noControlField, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );
        idPanelLayout.setVerticalGroup(
            idPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(idPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(controlRb1)
                    .addComponent(controlRb2)
                    .addComponent(controlRb3)
                    .addComponent(controlRb4)
                    .addComponent(controlRb5)
                    .addComponent(controlRb6)
                    .addComponent(noControlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        noControl.setText("No. Control");
        noControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noControlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ciudadPanelLayout = new javax.swing.GroupLayout(ciudadPanel);
        ciudadPanel.setLayout(ciudadPanelLayout);
        ciudadPanelLayout.setHorizontalGroup(
            ciudadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ciudadPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(ciudadField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        ciudadPanelLayout.setVerticalGroup(
            ciudadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ciudadPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ciudadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout domicilioPanelLayout = new javax.swing.GroupLayout(domicilioPanel);
        domicilioPanel.setLayout(domicilioPanelLayout);
        domicilioPanelLayout.setHorizontalGroup(
            domicilioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(domicilioPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(domicilioField, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        domicilioPanelLayout.setVerticalGroup(
            domicilioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(domicilioPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(domicilioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nombreCheckbox.setText("Nombre");
        nombreCheckbox.setToolTipText("");
        nombreCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCheckboxActionPerformed(evt);
            }
        });

        domicilioCheckbox.setText("Domicilio");
        domicilioCheckbox.setToolTipText("");
        domicilioCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domicilioCheckboxActionPerformed(evt);
            }
        });

        ciudadCheckbox.setText("Ciudad");
        ciudadCheckbox.setToolTipText("");
        ciudadCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ciudadCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ciudadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noControl)
                            .addComponent(nombreCheckbox)
                            .addComponent(domicilioCheckbox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombrePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(domicilioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(noControl)
                    .addComponent(idPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(nombrePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(domicilioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(nombreCheckbox)
                        .addGap(31, 31, 31)
                        .addComponent(domicilioCheckbox)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ciudadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ciudadCheckbox)
                        .addGap(11, 11, 11)))
                .addGap(27, 27, 27))
        );

        predicado.setText("Pred. Simple");
        predicado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                predicadoActionPerformed(evt);
            }
        });

        edadGroup.add(edadRb1);
        edadRb1.setText("<");

        edadGroup.add(edadRb4);
        edadRb4.setText(">=");

        edadGroup.add(edadRb2);
        edadRb2.setText(">");

        edadGroup.add(edadRb3);
        edadRb3.setText("<=");

        edadGroup.add(edadRb5);
        edadRb5.setText("=");

        edadGroup.add(edadRb6);
        edadRb6.setText("<>");
        edadRb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadRb6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout edadPanelLayout = new javax.swing.GroupLayout(edadPanel);
        edadPanel.setLayout(edadPanelLayout);
        edadPanelLayout.setHorizontalGroup(
            edadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edadPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(edadRb1)
                .addGap(22, 22, 22)
                .addComponent(edadRb2)
                .addGap(21, 21, 21)
                .addComponent(edadRb3)
                .addGap(18, 18, 18)
                .addComponent(edadRb4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edadRb5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edadRb6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edadField, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addContainerGap())
        );
        edadPanelLayout.setVerticalGroup(
            edadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edadPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(edadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edadRb1)
                    .addComponent(edadRb4)
                    .addComponent(edadRb2)
                    .addComponent(edadRb3)
                    .addComponent(edadRb5)
                    .addComponent(edadRb6)
                    .addComponent(edadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout oficioPanelLayout = new javax.swing.GroupLayout(oficioPanel);
        oficioPanel.setLayout(oficioPanelLayout);
        oficioPanelLayout.setHorizontalGroup(
            oficioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oficioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oficioField, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        oficioPanelLayout.setVerticalGroup(
            oficioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oficioPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(oficioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        edadCheckbox.setText("Edad");
        edadCheckbox.setToolTipText("");
        edadCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadCheckboxActionPerformed(evt);
            }
        });

        oficioCheckbox.setText("Oficio");
        oficioCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oficioCheckboxActionPerformed(evt);
            }
        });

        jButton2.setText("Limpiar Tabla");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(oficioCheckbox)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(edadCheckbox)
                                        .addGap(21, 21, 21)
                                        .addComponent(edadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(oficioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(predicado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(edadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(edadCheckbox)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(oficioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(oficioCheckbox)
                                .addGap(28, 28, 28))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(predicado)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void noControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noControlActionPerformed
        if(noControl.isSelected()){
            idPanel.setVisible(true);
        } else{
            idPanel.setVisible(false);
        }
    }//GEN-LAST:event_noControlActionPerformed

    private void controlRb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlRb6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_controlRb6ActionPerformed

    private void nombreCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCheckboxActionPerformed
        if(nombreCheckbox.isSelected()){
            nombrePanel.setVisible(true);
        } else{
            nombrePanel.setVisible(false);
        }
    }//GEN-LAST:event_nombreCheckboxActionPerformed

    private void oficioCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oficioCheckboxActionPerformed
        if(oficioCheckbox.isSelected()){
            oficioPanel.setVisible(true);
        } else{
            oficioPanel.setVisible(false);
        }
    }//GEN-LAST:event_oficioCheckboxActionPerformed

    private void edadCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadCheckboxActionPerformed
        if(edadCheckbox.isSelected()){
            edadPanel.setVisible(true);
        } else{
            edadPanel.setVisible(false);
        }
    }//GEN-LAST:event_edadCheckboxActionPerformed

    private void edadRb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadRb6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadRb6ActionPerformed

    private void domicilioCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domicilioCheckboxActionPerformed
        if(domicilioCheckbox.isSelected()){
            domicilioPanel.setVisible(true);
        } else{
            domicilioPanel.setVisible(false);
        }
    }//GEN-LAST:event_domicilioCheckboxActionPerformed

    private void ciudadCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadCheckboxActionPerformed
        if(ciudadCheckbox.isSelected()){
            ciudadPanel.setVisible(true);
        } else{
            ciudadPanel.setVisible(false);
        }
    }//GEN-LAST:event_ciudadCheckboxActionPerformed

    private void predicadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_predicadoActionPerformed

        String jdbcUrl = "jdbc:mysql://localhost:3306/dbd";
        String usuario = "root";
        String contraseña = "";
        

        try {
            // Establecer la conexión con la base de datos
            
            Connection conexion = DriverManager.getConnection(jdbcUrl, usuario, contraseña);

            Statement statement = conexion.createStatement();
            String nombreDelField="";
            String consulta = "SELECT * FROM practica2 WHERE ";
            int cont=0;
            
            if(noControl.isSelected()){
                nombreDelField = noControlField.getText();
                if(controlRb1.isSelected()){
                    consulta = consulta + "noControl " + "< " + nombreDelField + " ";
                } else if(controlRb2.isSelected()){
                    consulta = consulta + "noControl " + "> " + nombreDelField + " ";
                } else if(controlRb3.isSelected()){
                    consulta = consulta + "noControl " + "<= " + nombreDelField + " ";
                } else if(controlRb4.isSelected()){
                    consulta = consulta + "noControl " + "=> " + nombreDelField + " ";
                } else if(controlRb5.isSelected()){
                    consulta = consulta + "noControl " + "= " + nombreDelField + " ";
                } else {
                    consulta = consulta + "noControl " + "<> " + nombreDelField + " ";
                }
                cont++;
            }
            
            if(nombreCheckbox.isSelected()){
                nombreDelField = nombreField.getText();
                if(cont > 0){
                    consulta = consulta + "AND ";
                }
                consulta = consulta + "nombre = " + "'" + nombreDelField + "' ";
                cont++;
            }
            
            if(domicilioCheckbox.isSelected()){
                nombreDelField = domicilioField.getText();
                if(cont > 0){
                    consulta = consulta + "AND ";
                }
                consulta = consulta + "domicilio = " + "'" + nombreDelField + "' ";
                cont++;
            }
            
            if(ciudadCheckbox.isSelected()){
                nombreDelField = ciudadField.getText();
                if(cont > 0){
                    consulta = consulta + "AND ";
                }
                consulta = consulta + "ciudad = " + "'" + nombreDelField + "' ";
                cont++;
            }
            
            if(edadCheckbox.isSelected()){
                nombreDelField = edadField.getText();
                if(cont > 0){
                    consulta = consulta + "AND ";
                }
                if(edadRb1.isSelected()){
                    consulta = consulta + "edad " + "< " + nombreDelField + " ";
                } else if(edadRb2.isSelected()){
                    consulta = consulta + "edad " + "> " + nombreDelField + " ";
                } else if(edadRb3.isSelected()){
                    consulta = consulta + "edad " + "<= " + nombreDelField + " ";
                } else if(edadRb4.isSelected()){
                    consulta = consulta + "edad " + "=> " + nombreDelField + " ";
                } else if(edadRb5.isSelected()){
                    consulta = consulta + "edad " + "= " + nombreDelField + " ";
                } else {
                    consulta = consulta + "edad " + "<> " + nombreDelField + " ";
                }
                cont++;
            }
            
            
            if(oficioCheckbox.isSelected()){
                nombreDelField = oficioField.getText();
                if(cont > 0){
                    consulta = consulta + "AND ";
                }
                consulta = consulta + "oficio = " + "'" + nombreDelField + "' ";
                cont++;
            }


            ResultSet resultSet = statement.executeQuery(consulta);
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("No. Control");
            modelo.addColumn("Nombre");
            modelo.addColumn("Domicilio");
            modelo.addColumn("Ciudad");
            modelo.addColumn("Edad");
            modelo.addColumn("Oficio");

            while (resultSet.next()) {
                Object[] fila = new Object[6];
                fila[0] = resultSet.getInt("noControl"); 
                fila[1] = resultSet.getString("nombre"); 
                fila[2] = resultSet.getString("domicilio"); 
                fila[3] = resultSet.getString("ciudad"); 
                fila[4] = resultSet.getInt("edad"); 
                fila[5] = resultSet.getString("oficio"); 
                modelo.addRow(fila);
            }

           
             Tabla.setModel(modelo);

            conexion.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_predicadoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cargarDatos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cargarDatos() {
        String jdbcUrl = "jdbc:mysql://localhost:3306/dbd";
        String usuario = "root";
        String contraseña = "";
        

        try {
            
            Connection conexion = DriverManager.getConnection(jdbcUrl, usuario, contraseña);

            Statement statement = conexion.createStatement();

            String consulta = "SELECT * FROM practica2";
            ResultSet resultSet = statement.executeQuery(consulta);
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("No. Control");
            modelo.addColumn("Nombre");
            modelo.addColumn("Domicilio");
            modelo.addColumn("Ciudad");
            modelo.addColumn("Edad");
            modelo.addColumn("Oficio");

            while (resultSet.next()) {
                Object[] fila = new Object[6];
                fila[0] = resultSet.getInt("noControl"); 
                fila[1] = resultSet.getString("nombre"); 
                fila[2] = resultSet.getString("domicilio"); 
                fila[3] = resultSet.getString("ciudad"); 
                fila[4] = resultSet.getInt("edad"); 
                fila[5] = resultSet.getString("oficio"); 

                modelo.addRow(fila);
            }

            Tabla.setModel(modelo);

            // Cerrar la conexión cuando hayas terminado
            conexion.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
  
       
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelcito().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JCheckBox ciudadCheckbox;
    private javax.swing.JTextField ciudadField;
    private javax.swing.JPanel ciudadPanel;
    private javax.swing.JRadioButton controlRb1;
    private javax.swing.JRadioButton controlRb2;
    private javax.swing.JRadioButton controlRb3;
    private javax.swing.JRadioButton controlRb4;
    private javax.swing.JRadioButton controlRb5;
    private javax.swing.JRadioButton controlRb6;
    private javax.swing.JCheckBox domicilioCheckbox;
    private javax.swing.JTextField domicilioField;
    private javax.swing.JPanel domicilioPanel;
    private javax.swing.JCheckBox edadCheckbox;
    private javax.swing.JTextField edadField;
    private javax.swing.ButtonGroup edadGroup;
    private javax.swing.JPanel edadPanel;
    private javax.swing.JRadioButton edadRb1;
    private javax.swing.JRadioButton edadRb2;
    private javax.swing.JRadioButton edadRb3;
    private javax.swing.JRadioButton edadRb4;
    private javax.swing.JRadioButton edadRb5;
    private javax.swing.JRadioButton edadRb6;
    private javax.swing.JPanel idPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox noControl;
    private javax.swing.JTextField noControlField;
    private javax.swing.ButtonGroup noControlGroup;
    private javax.swing.JCheckBox nombreCheckbox;
    private javax.swing.JTextField nombreField;
    private javax.swing.JPanel nombrePanel;
    private javax.swing.JCheckBox oficioCheckbox;
    private javax.swing.JTextField oficioField;
    private javax.swing.JPanel oficioPanel;
    private javax.swing.JButton predicado;
    // End of variables declaration//GEN-END:variables
}
